-- Netflix Project

DROP TABLE IF EXISTS NETFLIX;
CREATE TABLE NETFLIX
(
		show_id	VARCHAR(6),
		type VARCHAR(10),
		title VARCHAR(150),
		director VARCHAR(208),
		castS		VARCHAR(1000),
		country	VARCHAR(150),
		date_added	VARCHAR(50),
		release_year INT,
		rating	VARCHAR(10),
		duration	VARCHAR(15),
		listed_in	VARCHAR(100),
		description	VARCHAR(250)
);

SELECT*FROM NETFLIX

SELECT
	COUNT(*) AS total_content
FROM NETFLIX;

SELECT 
	DISTINCT type
FROM NETFLIX

SELECT * FROM NETFLIX 

-- BUSINESS PROBLEM & SOLUTION 

--01.COUNT THE NUMBER OF MOVIES VS TV SHOWS

SELECT 
	type,
	COUNT(*) AS total_content
FROM NETFLIX
GROUP BY type

--02 FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS

SELECT 
		type,
		rating
FROM NETFLIX

SELECT
	type,
	rating
FROM
(

SELECT 
	type,
	rating,
	COUNT(*),
	RANK() OVER(PARTITION BY type ORDER BY COUNT(*)DESC) AS ranking
FROM NETFLIX
GROUP BY 1 , 2
) as t1
WHERE
ranking = 1
ORDER BY 1, 3 DESC

--03 LIST ALL MOVIES RELEASE IN A SPECIFIC YEAR (E.G., 2020)
--FILTER 2020
--MOVIES


SELECT * FROM NETFLIX
WHERE
	type ='Movie'
	AND
	release_year = 2020

--04. FIND THE TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFLIX

SELECT * FROM NETFLIX

SELECT 
	country,
	COUNT(show_id) AS total_content
FROM NETFLIX
GROUP BY 1

SELECT 
	UNNEST (STRING_TO_ARRAY(country,',') ) AS new_contry
	FROM NETFLIX


SELECT 
	UNNEST (STRING_TO_ARRAY(country,',') ) AS new_contry,
	COUNT(show_id) AS total_content
	FROM NETFLIX
	GROUP BY 1
	ORDER BY 2
	LIMIT 5
--05. IDENTIFY THE LONGEST MOVIES OR TV SHOWS CONTENT ON NETFLIX

SELECT * FROM NETFLIX
WHERE 
	type = 'Movie'
	AND duration = (SELECT MAX(duration) FROM NETFLIX)

--06. FIND CONTENT ADDED IN THE LAST 5 YEARS

SELECT 
	*,
	TO_DATE(date_added,'Month DD, YYYY')

SELECT
	*
FROM NETFLIX
WHERE
	 TO_DATE(date_added,'Month DD, YYYY') >= CURRENT_DATE - INTERVAL '5 years'

SELECT CURRENT_DATE - INTERVAL '5 years'
	
--07. FIND ALL THE MOVIES / TV SHOWS BY DIRECTOR 'RAJIV CHILAKA'

SELECT 
	*,
	SPILIT_PART(duration,',',1) AS sessons
FROM NETFLIX
WHERE 
	director LIKE '%Rajiv Chilaka%'

--08. LIST ALL TV SHOWS WITH MORE MAN 5 SEASONS

SELECT 
	* 
FROM NETFLIX
WHERE
	type = 'TV Show'
	AND
	SPLIT_PART(duration, ' ',1) ::numeric > 5 

SELECT
	SPLIT_PART('APPLE BANANA CHERRY',' ',1)

--09. COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE

SELECT 
	listed_in,
	show_id,
	UNNEST(STRING_TO_ARRAY(listed_in,' ,')) 
FROM NETFLIX

SELECT
	UNNEST(STRING_TO_ARRAY(listed_in,' ,')) AS genre,
	COUNT(show_id)
FROM NETFLIX
GROUP BY 1

--10. FIND EACH YEAR AND THE AVERAGE NUMBERS OF CONTENT RELEASE IN INDIA ON NETFLIX. RETRUN TOP 5 YEAR WITH HIGHEST AVG CONTENT RELEASE?


SELECT 
	TO_DATE(date_added, 'Month DD, YYYY') AS date,
	*
FROM NETFLIX
WHERE country = 'India'

TOTAL CONTENT 333/972

SELECT 
	EXTRACT(YEAR FROM TO_DATE(date_added, 'Month DD, YYYY')) AS year,
	COUNT(*),
	COUNT(*)::numeric/(SELECT COUNT(*) FROM NETFLIX WHERE country = 'India') ::numeric * 100 as avg_content_per_year
FROM NETFLIX
WHERE country = 'India'
GROUP BY 1


--11. LIST ALL MOVIES THAT ARE DOCUMENTARIES.

SELECT * FROM NETFLIX
WHERE
	listed_in ILIKE '%documentaries%'


--12.FIND ALL CONTENT WITHOUT A DIRECTOR

SELECT * FROM NETFLIX 
WHERE
	director IS NULL

--13. FIND HOW MANY MOVIES ACOR SALMAN KHAN APPREARED IN LAST 10 YEARS.

SELECT * FROM NETFLIX
WHERE 
	casts ILIKE '%salman khan%'
	AND 
	release_year > EXTRACT (YEAR FROM CURRENT_DATE) - 10


--14. FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED 

SELECT 
	show_id,
	casts,
	UNNEST(STRING_TO_ARRAY(casts,','))
FROM NETFLIX

SELECT
UNNEST(STRING_TO_ARRAY(casts,',')) as actores,
COUNT(*) AS total_content
FROM NETFLIX
WHERE country ILIKE '%India%'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

--15.CATEGORIES THE CONTENT BASED ON THE PRESENCE OF THE KEYWORDS KILL AND VIOLENCE IN DESCRIPTION FIELD. LABEL CONTENT CONTAINING THESE KNOWELEDGE AS BAD AND ALL OTHER CONTEN AS GOOD . COUNT HOW MANY ITEMSFALL INTO EACH CATEGORY.

SELECT 
*,
	CASE 
	WHEN description ILIKE '%kill%' 
	OR
	description ILIKE '%violence%' THEN 'Bad_Content'
	ELSE 'Good Content'
	END category
FROM NETFLIX

WHERE
	description ILIKE '%kill%'
	OR
	description ILIKE '%violence%'


WITH new_table
AS
(
SELECT 
*,
	CASE 
	WHEN description ILIKE '%kill%' 
	OR
	description ILIKE '%violence%' THEN 'Bad_Content'
	ELSE 'Good Content'
	END category
FROM NETFLIX
)
SELECT
	category,
	COUNT(*) AS total_content
	FROM new_table
	GROUP BY 1